// layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./navBar/page";
import GalleryFooter from "./footer/page";
import LayoutWrapper from "./layoutWrapper/layoutWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} max-h-[800px] bg-background` }>
        <LayoutWrapper
          navbar={<NavBar />}
          footer={<GalleryFooter />}
        >
          {children}
        </LayoutWrapper>
      </body>
    </html>
  );
}